name: Fix CSS and JS code style issues

on:
  push: [main]
  pull_request: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  css-and-js-code-styling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Fix CSS and JS code style issues
        run: biome check --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: fix code style issues"