name: Fix CSS and JS code style issues

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  css-and-js-code-styling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Fix CSS and JS code style issues
        run: |
            npm ci
            npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "ci: fix code style issues"
